#!/usr/bin/python
# -*- coding: utf-8 -*-

# Inspired by https://git.wiki.kernel.org/index.php/MarkEmptyDirs

import sys
import os
import argparse
import shutil

class opt:
    file = ""
    text = ""
    filename = '.gitignore'
    quiet = False
    mode = 'auto'
    real_mode = ""
    
def main():

    parse_argv()
    
    if opt.mode == 'auto':
        files_and_dirs = os.listdir('.')
        preferences = ['.git', '.hg', '.svn', '.cvs']

        for vcssys in preferences:
            if vcssys in files_and_dirs:
                opt.real_mode = vcssys[1:]
    else:
        opt.real_mode = opt.mode


    # We do an os.walk to detect empty dirs
    list_of_emptydirs = []
    for (dirpath, dirnames, filenames) in os.walk('.'):
        # We use topdown (default os.walk)
        # We prune .git et al dirs from dirname to stop recursing through them
        dirpruned = '.' + opt.real_mode

        if dirpruned in dirnames:
            dirnames.remove(dirpruned)

        if not dirnames and not filenames:
            # We skip the .git, .hg, .svn
            currdir = os.path.basename(dirpath)
            if currdir == '.' + opt.real_mode:
                continue

            list_of_emptydirs.append(dirpath)

    if not opt.quiet:
        print "empty dirs: %s " % list_of_emptydirs

    for emptydir in list_of_emptydirs:
        if opt.file:
            shutil.copyfile(opt.file, emptydir)
        else :
            with open(emptydir + '/' + opt.filename, 'w') as myfile:
                if opt.text:
                    myfile.write(opt.text + '\n')
                else:
                    if opt.real_mode == 'git':
                        # With git and quilt patches files cannot be empty neither
                        myfile.write("AUTOGENERATED TEXT:  Do not erase this directory\n")


    print "Marked %d directories" % len(list_of_emptydirs)

    
def parse_argv() :

    parser = argparse.ArgumentParser(description='create empty or template files in empty directories')

    parser.add_argument('--file',
                        help = 'Template file to copy to every empty directory')

    parser.add_argument('--text',
                        help = 'Text to place in the empty file')

    parser.add_argument('--filename',
                        default = opt.filename,
                        help = 'Filename to use (default .gitignore)')

    parser.add_argument('--quiet',
                        action = 'store_true',
                        help = 'Do not print the list of directories')
                        
    parser.add_argument('--mode',
                        default = opt.mode,
                        help = 'auto, git, svn, hg or CVS')

    args = parser.parse_args()

    opt.file = args.file
    opt.text = args.text
    opt.filename = args.filename
    opt.quiet = args.quiet
    opt.mode = args.mode

if __name__ == '__main__':
    main()
